'use strict';


module.exports = {
    
    REGISTER_HOST_REQUEST: 0,
    REGISTER_HOST_RESPONSE: 1,
    PENDING_HOST: 2,
    REGISTER_PENDING_HOST_REQUEST: 3,
    REGISTER_PENDING_HOST_RESPONSE: 4,
    PING: 6,
    PONG: 7
};